Card size smaller with no commit information (#2476)
redhat-developer/gitops-console-plugin pull request #14
Opened 2022-12-20 18:56 UTC by keithchong

See 2476 for more details

Signed-off-by: Keith Chong <kykchong@redhat.com>

2022-12-20 20:45 UTC, ciiay requested changes
Seems like it's missing locales for the new contents. Other than that looks good to me. Left two small comments.

2022-12-21 00:43 UTC, keithchong commented on src/components/EnvironmentDetailsPage.tsx
> +        console.log("data is " + data);
I removed it.

2022-12-21 00:46 UTC, keithchong commented on package.json
> +    "dev": "yarn clean && REACT_REFRESH=true NODE_OPTIONS=--max-old-space-size=4096 yarn ts-node ./node_modules/.bin/webpack serve --mode=development --progress",
This was the dev mode just like what we had in the static plugin. I was using it and it seemed ok to me.  It's like `start`.   I've removed it.

2023-01-03 20:00 UTC, ciiay commented
LGTM.
We still need to update local files for other languages too. Shall we keep a note somewhere?

2023-01-03 20:27 UTC, ciiay approved these changes

2023-01-03 20:27 UTC, merged